use("app")

db.conjugations.drop()
db.createCollection("conjugations")

db.conjugations.insertMany([
  {
    sentence: "Yo _____ (comer)...",
    answer: "como",
    translation: "I eat...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (vivir)...",
    answer: "vives",
    translation: "You live...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Él _____ (leer)...",
    answer: "lee",
    translation: "He reads...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (trabajar)...",
    answer: "trabajamos",
    translation: "We work...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Ellos _____ (estudiar)...",
    answer: "estudian",
    translation: "They study...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Ella _____ (beber)...",
    answer: "bebe",
    translation: "She drinks...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Ustedes _____ (correr)...",
    answer: "corren",
    translation: "You all run...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (escribir)...",
    answer: "escribo",
    translation: "I write...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (hablar)...",
    answer: "hablas",
    translation: "You speak...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (viajar)...",
    answer: "viajamos",
    translation: "We travel...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Él _____ (caminar)...",
    answer: "camina",
    translation: "He walks...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Ellos _____ (abrir)...",
    answer: "abren",
    translation: "They open...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (mirar)...",
    answer: "miro",
    translation: "I watch...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (bailar)...",
    answer: "bailas",
    translation: "You dance...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Ustedes _____ (escuchar)...",
    answer: "escuchan",
    translation: "You all listen...",
    tense: "presente",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (comer)...",
    answer: "comí",
    translation: "I ate...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (vivir)...",
    answer: "viviste",
    translation: "You lived...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Él _____ (leer)...",
    answer: "leyó",
    translation: "He read...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (trabajar)...",
    answer: "trabajamos",
    translation: "We worked...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Ellos _____ (estudiar)...",
    answer: "estudiaron",
    translation: "They studied...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Ella _____ (beber)...",
    answer: "bebió",
    translation: "She drank...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Ustedes _____ (correr)...",
    answer: "corrieron",
    translation: "You all ran...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (escribir)...",
    answer: "escribí",
    translation: "I wrote...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (hablar)...",
    answer: "hablaste",
    translation: "You spoke...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (viajar)...",
    answer: "viajamos",
    translation: "We traveled...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Él _____ (caminar)...",
    answer: "caminó",
    translation: "He walked...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Ellos _____ (abrir)...",
    answer: "abrieron",
    translation: "They opened...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (mirar)...",
    answer: "miré",
    translation: "I watched...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (bailar)...",
    answer: "bailaste",
    translation: "You danced...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Ustedes _____ (escuchar)...",
    answer: "escucharon",
    translation: "You all listened...",
    tense: "pretérito indefinido",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (comer)...",
    answer: "comía",
    translation: "I used to eat...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (vivir)...",
    answer: "vivías",
    translation: "You used to live...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Él _____ (leer)...",
    answer: "leía",
    translation: "He used to read...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (trabajar)...",
    answer: "trabajábamos",
    translation: "We used to work...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Ellos _____ (estudiar)...",
    answer: "estudiaban",
    translation: "They used to study...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Ella _____ (beber)...",
    answer: "bebía",
    translation: "She used to drink...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Ustedes _____ (correr)...",
    answer: "corrían",
    translation: "You all used to run...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (escribir)...",
    answer: "escribía",
    translation: "I used to write...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (hablar)...",
    answer: "hablabas",
    translation: "You used to speak...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (viajar)...",
    answer: "viajábamos",
    translation: "We used to travel...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Él _____ (caminar)...",
    answer: "caminaba",
    translation: "He used to walk...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Ellos _____ (abrir)...",
    answer: "abrían",
    translation: "They used to open...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (mirar)...",
    answer: "miraba",
    translation: "I used to watch...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (bailar)...",
    answer: "bailabas",
    translation: "You used to dance...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Ustedes _____ (escuchar)...",
    answer: "escuchaban",
    translation: "You all used to listen...",
    tense: "imperfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (comer)...",
    answer: "comeré",
    translation: "I will eat...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (vivir)...",
    answer: "vivirás",
    translation: "You will live...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Él _____ (leer)...",
    answer: "leerá",
    translation: "He will read...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (trabajar)...",
    answer: "trabajaremos",
    translation: "We will work...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Ellos _____ (estudiar)...",
    answer: "estudiarán",
    translation: "They will study...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Ella _____ (beber)...",
    answer: "beberá",
    translation: "She will drink...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Ustedes _____ (correr)...",
    answer: "correrán",
    translation: "You all will run...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (escribir)...",
    answer: "escribiré",
    translation: "I will write...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (hablar)...",
    answer: "hablarás",
    translation: "You will speak...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (viajar)...",
    answer: "viajaremos",
    translation: "We will travel...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Él _____ (caminar)...",
    answer: "caminará",
    translation: "He will walk...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Ellos _____ (abrir)...",
    answer: "abrirán",
    translation: "They will open...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (mirar)...",
    answer: "miraré",
    translation: "I will watch...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (bailar)...",
    answer: "bailarás",
    translation: "You will dance...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Ustedes _____ (escuchar)...",
    answer: "escucharán",
    translation: "You all will listen...",
    tense: "futuro",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (estudiar)...",
    answer: "he estudiado",
    translation: "I have studied...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Ella _____ (comer)...",
    answer: "ha comido",
    translation: "She has eaten...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (viajar)...",
    answer: "hemos viajado",
    translation: "We have traveled...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (leer)...",
    answer: "has leído",
    translation: "You have read...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Ellos _____ (vivir)...",
    answer: "han vivido",
    translation: "They have lived...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (hacer)...",
    answer: "he hecho",
    translation: "I have done...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (ver)...",
    answer: "has visto",
    translation: "You have seen...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (abrir)...",
    answer: "hemos abierto",
    translation: "We have opened...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Ella _____ (romper)...",
    answer: "ha roto",
    translation: "She has broken...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Ustedes _____ (escribir)...",
    answer: "han escrito",
    translation: "You all have written...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Yo _____ (decir)...",
    answer: "he dicho",
    translation: "I have said...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Él _____ (trabajar)...",
    answer: "ha trabajado",
    translation: "He has worked...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Nosotros _____ (caminar)...",
    answer: "hemos caminado",
    translation: "We have walked...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Tú _____ (beber)...",
    answer: "has bebido",
    translation: "You have drunk...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
  {
    sentence: "Ellos _____ (jugar)...",
    answer: "han jugado",
    translation: "They have played...",
    tense: "presente perfecto",
    difficulty: "beginner",
  },
]);

db.passages.drop()
db.createCollection("passages")

db.passages.insertMany()