export const CONTROL_CONFIG = {
  grammar: {
    title: "Grammar Setup",
    generateLabel: "New Questions",
    questionOptions: [5, 10, 15],
    tenseOptions: [
      "Presente",
      "Preterite",
      "Imperfecto",
      "Futuro",
      "Condicional",
    ],
    showTense: true,
    showTopic: false,
    showSearch: false,
    showQuestionOptions: true,
  },
  reading: {
    title: "Reading Setup",
    generateLabel: "New Passage",
    questionOptions: [3, 5, 8],
    topicOptions: ["Culture", "History", "People", "Science"],
    showTense: false,
    showTopic: true,
    showSearch: true,
    showQuestionOptions: true,
  },
  speech: {
    title: "Conversation Setup",
    generateLabel: "New Prompt",
    topicLabel: "Conversation Type",
    topicOptions: [
      "Presentation Formal speech",
      "Casual conversation",
      "Storytelling",
      "Debate/Argument",
      "Interview responses",
      "Impromptu speaking",
    ],
    showTense: false,
    showTopic: true,
    showSearch: false,
    showQuestionOptions: false,
  },
};
