"""reconcile local-first schema

Revision ID: ad4e13ed0bb1
Revises: 39347f27a5f5
Create Date: 2026-08-03 01:38:13.817818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad4e13ed0bb1'
down_revision: Union[str, Sequence[str], None] = '39347f27a5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Preserve existing description text inside metadata before dropping the column.
    op.execute(
        "UPDATE concepts SET metadata = COALESCE(metadata, '{}'::jsonb) "
        "|| jsonb_build_object('description', description) "
        "WHERE description IS NOT NULL"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('concepts', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('concepts', 'description')
    op.drop_constraint(op.f('exercise_concepts_exercise_id_fkey'), 'exercise_concepts', type_='foreignkey')
    op.drop_constraint(op.f('exercise_concepts_concept_id_fkey'), 'exercise_concepts', type_='foreignkey')
    op.create_foreign_key(None, 'exercise_concepts', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exercise_concepts', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    op.add_column('exercises', sa.Column('topic', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('cefr_level', sa.Text(), nullable=True))
    op.drop_column('exercises', 'media_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'cefr_level')
    op.drop_column('exercises', 'topic')
    op.drop_constraint(None, 'exercise_concepts', type_='foreignkey')
    op.drop_constraint(None, 'exercise_concepts', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_concepts_concept_id_fkey'), 'exercise_concepts', 'concepts', ['concept_id'], ['id'])
    op.create_foreign_key(op.f('exercise_concepts_exercise_id_fkey'), 'exercise_concepts', 'exercises', ['exercise_id'], ['id'])
    op.add_column('concepts', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('concepts', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
